---
title             : "Quantifying the syntactic bootstrapping effect in verb learning through meta-analysis"
shorttitle        : "Syntactic Bootstrapping MA"
author:  
  - name          : "Anjie Cao"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "what is this" # <- your physical address at Stanford (something something Jordan Hall - it's a weird relic of when people actually sent stuff in snail mail)
    email         : "anjiecao@stanford.edu" # <- probably want your new stanford email
  - name          : "Molly Y. Lewis"
    affiliation   : "2"
    email         : ""
affiliation:
    
  - id            : "1"
    institution   : "Department of Psychology, Stanford University"
  - id            : "2"
    institution   : "Department of Psychology, Carnegie Mellon Unviversity"
author_note: |
  okie
abstract: |
  Learning verbs is more challenging than learning nouns because verbs’ references are ephemeral, ever-changing actions. One proposed verb learning mechanism is Syntactic Bootstrapping, the phenomena that young children can use syntactic information in the sentences to infer the meaning of a novel verb. For example, if a child hears the sentence “The bunny is gorping the duck”, the child can rely on the transitive structure to infer the reference of “gorping” is the causative action the bunny imposes on the duck. This learning strategy is first demonstrated by a seminal study by Naigles (1990), and in the last three decades, there have been a vast number of empirical studies that investigated this phenomena using many variations of the empirical paradigms. Here in this paper we presented the first quantitative of the syntactic bootstrapping literature by using a meta-analytic approach. We found evidence for publication bias, but the bias alone can not account for the albeit small effect size. In addition, we also showed that the effect is only present in studies using transitive sentences, and there was no evidence for an age effect. Furthermore, Methodological variations did not significantly change the effect size. We concluded that the small effect size and the absence of the effect in intransitive conditions raised the issues of generalizability of syntactic bootstrapping. We concluded that more well-powered direct replication of the syntactic bootstrapping study is needed to better understand the nature and the developmental trajectory of syntactic bootstrapping. 

  
keywords          : "language acquisition, syntactic bootstrapping, meta-analysis"
wordcount         : ""
bibliography      : ["references.bib"]
csl               : "apa6-meta.csl"
header-includes:
  - \usepackage{setspace}
  - \usepackage{float}
  - \usepackage{graphicx}
  - \AtBeginEnvironment{tabular}{\singlespacing}
  - \usepackage{pbox}
  - \usepackage{hyphsubst}
  - \floatplacement{figure}{t!} # make every figure with caption = t
figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
always_allow_html : true
#lang              : "english"
documentclass     : "apa6"
class             : "man"
output:
  papaja::apa6_pdf:  #word_document 
    latex_engine: xelatex # this solved an encoding issue
  #always_allow_html: true
---

```{r load_utility_packages, include = FALSE}
library(papaja)
library(rmarkdown)
library(tidyverse) 
library(here)
library(glue)
library(metafor)
library(knitr)
library(PublicationBias)
library(janitor)
library(insight)
library(patchwork)
library(metalabr)


# scripts for data presentation
source(here("writeups/paper/scripts/prisma_diagram.R"))
source(here("writeups/paper/scripts/model_print.R"))
source(here("writeups/paper/scripts/forest_plot_helper.R"))
source(here("writeups/paper/scripts/funnel_plot_helper.R"))
source(here("writeups/paper/scripts/predictor_plot_helper.R"))
source(here("writeups/paper/scripts/metalab_plot_helper.R"))
```


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      cache = FALSE,
                      echo = FALSE,
                      fig.pos = "t!")
knitr::opts_chunk$set(dev = 'pdf')

theme_set(theme_classic(base_size = 11))
```

```{r constant}
alpha <- .05
CRIT_95 <- 1.96
CRIT_99 <- 2.58
```


# Introduction
```{r child = "sections/01_intro.Rmd"}
```

# Method
```{r child = "sections/02_method.Rmd"}
```

# Results
```{r child = "sections/03_results.Rmd"}
```

# General Discussion
```{r child = "sections/04_discussion.Rmd"}
```

\newpage

# References

---
nocite: | @fenson2000short
...
  
```{r appendix}
#render_appendix("appendix.Rmd")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
