---
title: "MA_SB_check_empty"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(knitr)

```

```{r cars}

DATA_PATH <- here("data/processed/syntactic_bootstrapping_tidy_data.csv") # make all variables (i.e. things that might change) as capital letters at the top of the scripts

ma_data <- read_csv(DATA_PATH)   %>%
  filter(language == "English",
         population_type == "typically_developing", 
         stimuli_modality == "video"|stimuli_modality == "animation",
         !is.na(mean_age))

# missing vocab
ma_data %>% filter(is.na(productive_vocab_mean) & is.na(productive_vocab_median)) 
# transitive missing patient argument
ma_data %>% filter(is.na(patient_argument_type) & sentence_structure == "transitive") 
# intransitive all have no patient argument, maybe needs to be changed to something else
ma_data %>% filter(!is.na(patient_argument_type) & sentence_structure == "intransitive" ) # error needs to be fixed

# missing n_repetition sentence, needs to be filled in
ma_data %>% filter(is.na(n_repetitions_sentence)) #needs to be filled in 
# missing n_repetition video, needs to be filled in
ma_data %>% filter(is.na(n_repetitions_video)) 
# missing test question
ma_data %>% filter(is.na(test_question)) 

ma_data %>% filter(is.na(patient_argument_type_clean))
ma_data %>% filter(sentence_structure == "intransitive")
ma_data %>% filter(is.na(patient_argument_type_clean)) %>% filter(sentence_structure == "intransitive")
ma_data %>% filter(is.na(agent_argument_type_clean))

```
```{r}
ma_data %>% filter(is.na(patient_argument_type_clean))
```

