---
title: "long dataframe "
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      cache = FALSE,
                      #echo = FALSE,
                      fig.pos = "t!")
```



```{r}
library(papaja)
library(rmarkdown)
library(tidyverse) 
library(here)
library(glue)
library(metafor)
library(knitr)
library(gridExtra)
library(here)
library(heatmaply)
library(MuMIn)
library(glmulti)
library(PRISMAstatement)
library(PublicationBias)

DATA_PATH <- here("data/processed/syntactic_bootstrapping_tidy_data.csv") 
RAW_DATA_PATH <- here("data/raw/syntactic_bootstrapping_raw_data.csv")

ma_data <- read_csv(DATA_PATH) %>% mutate(row_id = 1:n())

mine <- read_csv(here("data/processed/syntactic_bootstrapping_tidy_data.csv"))
molly <- read_csv(here("data/processed/syntactic_bootstrapping_tidy_data_molly.csv"))
```


```{r}
setdiff(mine$x_1, molly$x_1) 
setdiff(mine$unique_id,molly$unique_id)
setdiff(mine$sd_1, molly$sd_1)
setdiff(mine$d_calc, molly$d_calc)

```
```{r}
base_model_no_mv_molly <-  rma(d_calc,  d_var_calc, data=molly)
base_model_no_mv_my <- rma(d_calc,  d_var_calc, data=mine)
```

```{r}
trimfill(base_model_no_mv)
trimfill(base_model_no_mv_my)
```



```{r}
rma.glmulti <- function(formula,data)
  {rma.mv(formula, d_var_calc, data=ma_data, method="ML")
}
res <- glmulti(d_calc ~ stimuli_modality + stimuli_actor + test_mass_or_distributed + n_repetitions_sentence + practice_phase + character_identification + test_method, data=ma_data,
               level=1, fitfunction=rma.glmulti, crit="aicc", confsetsize=32)
```
```{r}
top <- weightable(res)
top <- top[top$aicc <= min(top$aicc) + 2,]
top
```
```{r}
summary(res@objects[[1]])
plot(res, type="s")

```
```{r}
ma_data <- ma_data %>% mutate(row_id = 1:n()) %>% select(d_var_calc)
```


```{r}
 rma.mv(d_calc ~   test_mass_or_distributed   +
                  character_identification + 
                  test_method +
                  agent_argument_type2 +
                  sentence_structure + 
                  mean_age,
                  V = d_var_calc, 
       random = ~ 1 | short_cite/same_infant/row_id, data = ma_data)
```

```{r}
mega <- rma(d_calc ~ test_mass_or_distributed   +
                  character_identification + 
                  test_method +
                  agent_argument_type2 +
                  sentence_structure + 
                  mean_age,
                  vi = d_var_calc, 
       random = ~ 1 | short_cite/same_infant/row_id, data = ma_data)
```


```{r}
regtest(mega)
```

```{r}
p <- predict(mega) 
p
```



```{r}
m<-rma.uni(d_calc,vi = d_var_calc, 
       random = ~ 1 | short_cite/same_infant/row_id, data = ma_data)


tf<-trimfill(m)
summary(m)
summary(tf)
```

```{r}
trimfill(base_model_no_mv)
```



```{r}
base_model_no_mv <-  rma(d_calc,  d_var_calc, data=ma_data)
regtest(base_model_no_mv, predictor = 'sei')
```

```{r}
fsn(ma_data$d_calc, ma_data$d_var_calc, type="Orwin", alpha=.05, target = 0.01)
fsn(p$pred, p$se, type="Orwin", alpha=.05, target = 0.01)

```


```{r}
corrected_meta(
ma_data$d_calc,
ma_data$d_var_calc,
eta=,
clustervar = 1:length(ma_data$d_calc),
model = "robust",
selection.tails = 1,
favor.positive = TRUE,
alpha.select = 0.05,
CI.level = 0.95,
small = TRUE
)
```
```{r}
pval_plot(ma_data$d_calc,
ma_data$d_var_calc, alpha.select = 0.05) 
```

```{r}
significance_funnel(
ma_data$d_calc,
ma_data$d_var_calc,
xmin = min(ma_data$d_calc),
xmax = max(ma_data$d_calc),
ymin = 0,
ymax = max(sqrt(ma_data$d_var_calc)),
xlab = "Point estimate",
ylab = "Estimated standard error",
favor.positive = TRUE,
est.all = NA,
est.N = NA,
alpha.select = 0.05,
plot.pooled = TRUE
)
```

```{r}
svalue(
ma_data$d_calc,
ma_data$d_var_calc,
q = 0.0,
clustervar = 1:length(ma_data$d_calc),
model = "robust",
alpha.select = 0.05,
eta.grid.hi = 200,
favor.positive = TRUE,
CI.level = 0.95,
small = TRUE,
return.worst.meta = FALSE
)
```



```{r}
get_MA_params <- function(moderator, df) {
  
  this_data <- df
  n = nrow(this_data)
  
  if (moderator == "mean_age"){
      model <- rma.mv(d_calc ~ log(mean_age), V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]

  } else if (moderator == "NULL"){
      model <- rma.mv(d_calc, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- NA
      this_moderator_estimate.cil <- NA
      this_moderator_estimate.cih <- NA
      this_moderator_z <- NA
      this_moderator_p <- NA
    
  }else if (moderator == "sentence_structure"){
    model <- rma.mv(d_calc~sentence_structure, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
  }else if (moderator == "productive_vocab_median"){
    model <- rma.mv(d_calc~productive_vocab_median, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
  }else if (moderator == "agent_argument_type_clean"){
    model <- rma.mv(d_calc~agent_argument_type_clean, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "patient_argument_type_clean"){
    model <- rma.mv(d_calc~patient_argument_type_clean, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "agent_argument_number"){
    model <- rma.mv(d_calc~agent_argument_number, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "n_repetitions_sentence"){
    model <- rma.mv(d_calc~n_repetitions_sentence, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
  }else if (moderator == "stimuli_modality"){
     model <- rma.mv(d_calc~stimuli_modality, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
    
  }else if (moderator == "n_repetitions_video"){
    model <- rma.mv(d_calc~n_repetitions_video, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
    
  }else if (moderator == "stimuli_actor"){
    model <- rma.mv(d_calc~stimuli_actor, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
  }else if (moderator == "transitive_event_type"){
    model <- rma.mv(d_calc~transitive_event_type, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "intransitive_event_type"){
    model <- rma.mv(d_calc~intransitive_event_type, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "visual_stimuli_pair"){
    model <- rma.mv(d_calc~visual_stimuli_pair, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "test_method"){
    model <- rma.mv(d_calc~test_method, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "presentation_type"){
    model <- rma.mv(d_calc~presentation_type, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "character_identification"){
    model <- rma.mv(d_calc~character_identification, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "practice_phase"){
     model <- rma.mv(d_calc~practice_phase, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
    
  }else if (moderator == "test_mass_or_distributed"){
    model <- rma.mv(d_calc~test_mass_or_distributed, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "n_train_test_pair"){
     model <- rma.mv(d_calc~n_train_test_pair, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }else if (moderator == "n_test_trial_per_pair"){
    model <- rma.mv(d_calc~n_test_trial_per_pair, V = d_var_calc,
                      random = ~ 1 | short_cite/same_infant/x_1,
                      method = "REML",
                      data = this_data)
      
      this_moderator_estimate <- model$b[2]
      this_moderator_estimate.cil <- model$ci.lb[2]
      this_moderator_estimate.cih <- model$ci.ub[2]
      this_moderator_z <- model$zval[2]
      this_moderator_p <- model$pval[2]
    
  }
  
  params <- data.frame(this_moderator = moderator,
                       n = n,
                       estimate = model$b[1],
                       estimate.cil = model$ci.lb[1],
                       estimate.cih = model$ci.ub[1],
                       z = model$zval[1],
                       p = model$pval[1],
                       mod_estimate = this_moderator_estimate,
                       mod_estimate.cil = this_moderator_estimate.cil, 
                       mod_estimate.cih = this_moderator_estimate.cih,
                       moderator_z = this_moderator_z,
                       moderator_p = this_moderator_p,
                       Q = model$QE,
                       Qp = model$QEp)
}


v <- c( "NULL", "mean_age","productive_vocab_median", "sentence_structure", "agent_argument_type_clean", "patient_argument_type_clean","agent_argument_number", "n_repetitions_sentence", "n_repetitions_video", "stimuli_modality", "stimuli_actor", "transitive_event_type","intransitive_event_type", "visual_stimuli_pair", "test_method","presentation_type","character_identification", "practice_phase", "test_mass_or_distributed", "n_train_test_pair", "n_test_trial_per_pair" )


all_models <- map_df(v,ma_data, .f = get_MA_params)
  
all_models

mod_print <- all_models %>%
             mutate(esimate_print =  round(estimate, 2),
                    CI_print = paste0(" [", 
                                      round(estimate.cil, 2),
                                     ", ",
                                     round(estimate.cih, 2),
                                     "]"),
                   estimate_print_full = paste(esimate_print, CI_print),
                   z_print = round(z, 2),
                   p_print = round(p, 2),
                   p_print = ifelse(p_print <.001, "<.001", paste0("= ", p_print)),
                   mod_estimate_print = round(mod_estimate, 2),
                   mod_CI_print = paste0(" [", 
                                      round(mod_estimate.cil, 2),
                                     ", ",
                                     round(mod_estimate.cih, 2),
                                     "]"),
                   mod_estimate_print_full = paste(mod_estimate_print, mod_CI_print),

                   mod_z_print =  round(moderator_z, 2),
                   mod_p_print =  round(moderator_p, 2),
                   mod_p_print = ifelse(mod_p_print < .001, "<.001", 
                                        paste0("= ", mod_p_print)),
                   Q_print = round(Q, 2),
                   Qp_print = round(Qp, 2),
                   Qp_print = ifelse(Qp_print < .001, "<.001", paste0("= ", Qp_print)))
mod_print
```

```{r}

mod_print_plot <- mod_print %>% mutate(
  p_val = case_when(
    moderator_p < 0.05 ~ "<0.05",
    moderator_p > 0.05 & moderator_p < 0.1 ~ "0.05<p<0.1",
    TRUE ~ "NS"
  )
)


mod_print_plot %>% 
  ggplot(aes(x = this_moderator, y = mod_estimate, color = moderator_p)) + 
  geom_point(size = 2) + 
  geom_linerange(aes(ymin =  mod_estimate.cil, ymax =  mod_estimate.cih)) + 
  geom_hline(aes(yintercept = 0), linetype = 2) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  coord_flip()

mod_print_plot %>% 
  ggplot(aes(x = this_moderator, y = mod_estimate, color = p_val)) + 
  geom_point(size = 2) + 
  geom_linerange(aes(ymin =  mod_estimate.cil, ymax =  mod_estimate.cih)) + 
  geom_hline(aes(yintercept = 0), linetype = 2) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  coord_flip()
  
```



