
Three decades of research on syntactic bootstrapping have examined the role that syntax plays in facilitating early verb acquisition. Here we built upon these previous studies by presenting a quantitative synthesis of the literature using meta-analytic methods. We find a small effect of syntactic bootstrapping, comparable in size to that of sound-symbolism and cross-situational learning.  We then used the meta-analytic method to examine how the strength of the syntactic bootstrapping effect varies as a function of developmental change and syntactic structure.  We found no evidence that the strength of the syntactic bootstrapping effect changes across development, or varies as a function of different types of noun phrase structures. In contrast, we found some evidence that the strength of the effect is influenced by predicate type: the syntactic bootstrapping effect is present for transitive sentences, but not intransitive sentences. We also examined a range of methodological features and found no evidence that these features had an appreciable moderating influence on the size of the syntactic bootstrapping effect. We conclude by discussing several key implications of our findings. 

## Small effect size

The syntactic bootstrapping effect (*d* = `r filter(mod_print, moderator == "NULL")$estimate_print`) is small by conventional Cohen's *d* standards [@cohen:statistical], even in the presence of some publication bias. It is also small relative to other early word learning biases and strategies typically studied with nouns, like mutual exclusivity and gaze-following. On the one hand, this small effect size is consonant with the fact that verbs tend to be learned later in development than nouns [e.g. @bates1994; @frank2019variability]. If verb learning strategies are weaker than those for nouns, we would expect verbs to be learned later. On the other hand, children do eventually develop a large vocabulary of verbs, despite no developmental change in the strength of the syntactic bootstrapping effect. This raises an important puzzle: If the syntactic bootstrapping effect is relatively weak, how do children learn a large vocabulary of verbs?

One possibility is that, although the syntactic bootstrapping effect is relatively weak when measured in the laboratory, it plays a more prominent role in verb learning “in the wild”. This could be true if there were many opportunities for syntactic bootstrapping that occurred in naturalistic input, relative to the sort of input required for other verb learning strategies like sound symbolism. The strength of the syntactic bootstrapping effect could also be affected by the particular task demands of the paradigm. Estimates of effect size are necessarily tied to the implementation in a particular paradigm, and it is possible that the syntactic bootstrapping paradigm is particularly challenging for children. However, at least at first pass, the paradigms used to test these different strategies are highly comparable. Further, researchers typically aim to maximize effect size in designing studies, making different paradigms for testing different phenomena highly comparable as best-case scenarios for observing the target effect. While we suspect that the observed small syntactic bootstrapping effect is not due to constraints of its implementation in the laboratory, adequately addressing this question requires future work combining controlled experimental paradigms with large-scale descriptive work of naturalistic input.

A second possibility is that children learn verbs using many of the same strategies typically thought of as noun learning strategies. Many word learning strategies are considered to be better for learning concrete nouns, where the perceptual information tends to be stable and less complex. The perceptual complexity of verbs relative to nouns may partially account for the smaller effect size of syntactic bootstrapping---a verb learning strategy---relative to the other strategies we consider, which are primarily tested with nouns [@zhou2021].  Nevertheless, there is some evidence that a wide range of word learning strategies may be helpful in verb learning, in addition to syntactic bootstrapping. Mutual exclusivity [@merriman1993four; @golinkoff1996lexical; @merriman1996young], cross-situational learning [@scott20122; @monaghan2015gavagai], sound symbolism [@kantartzis2011japanese; @imai2008sound] and social cues [@tomasello1994learning; @roseberry2009live] have all been found to facilitate the mapping between verbs and actions. Importantly, these learning strategies, including syntactic bootstrapping, are not mutually exclusive with one another: children may be using a combination of strategies to varying degrees in different contexts and at different ages. Further, different word learning strategies may be more or less suited for learning different types of words, andthe reliance on different strategies may change with development. For example, it is unclear how a learner would acquire a meaning without a direct perceptual correlate (e.g., “think”, “democracy”) without relying heavily on information in the linguistic context [@gillette1999human; @landauer1997solution]. Understanding how these different strategies are flexibly used in verb learning is an important area for future research.

## No developmental change

Notably, we do not find the syntactic bootstrapping effect gets larger with development across the age range in our sample (`r round(min_age_months, 0)`-`r round(max_age_months, 0)` months). This pattern is consistent with the proposal that syntactic bootstrapping is an unlearned bias and that the accumulation of experience with age does not have a significant impact on the strength of the  effect [@fisher2020developmental; @gleitman1990structural]. An alternative explanation for the lack of developmental change is the relational nature of verbs and grammatical constructions [@gentner2006verbs; @goldwater2017grammatical]. It is possible that developmental change only emerges as children experience the “relational shift”, that is, a developmental shift in their attention from objects to the relations between objects [@gentner1988metaphor; @gentner1991language]. As children become more attuned to the relations around them, the ability to learn relational words like verbs may also improve. There is also some evidence to suggest that older children are more likely to rely on syntactic information to infer verb meaning: @nappa2009use found that 5-year-olds  were more likely than 3-year-olds to rely on syntactic cues relative to socio-pragmatic cues when both sources of information were present. It is therefore possible that although no developmental change was observed within the age range of the current meta-analysis, syntactic information may play a more prominent role in verb learning later on in development. 

A final possibility is that researchers make methodological adaptations for children of different ages, such that older children are tested in more challenging paradigms than younger children. Under this possibility, we do not observe a developmental increase in the size of the effect because of children’s increasing ability to use syntactic information to infer meaning is concealed by more challenging task demands. We examined this hypothesis in the current meta-analysis by testing whether a wide range of methodological factors interacted with age, and we found no evidence that they did. We also informally examined how the complexity of the visual stimuli used in the studies in our meta-analysis varied as a function of age (see SI, Sec. 8). With the exception of one study designed for 15-month-olds [@jin2015role], there was no observable variability in visual stimuli complexity as a function of the age of children tested. While it is of course possible that there is a relevant, unmeasured methodological factor, the present set of analyses are suggestive that the lack of developmental change in the strength of effect is not due to methodological factors. 

## Transitivity effect 

Our meta-analysis revealed that the syntactic bootstrapping effect is only observed with certain kinds of syntactic structures: children tend to select the correct novel action in conditions using transitive sentences (e.g., “The girl is gorping the boy”), but not in conditions using intransitive sentences (e.g., “The girl is gorping”). This pattern is consistent with the observations that several researchers have made [@yuan2012counting; @arunachalam2010meaning]. Three factors may have given rise to this transitivity advantage. First, linguistic information can only be useful in narrowing the hypothesis space to the extent that it distinguishes between potential meanings in the observed context [@gleitman1990structural; @gleitman1994words; @fisher1994better]. Notably, under certain contexts, transitive sentences are less ambiguous than intransitive sentences. If, for example, one scene shows a girl patting a boy (causative), and a second scene shows of a girl and boy jumping side-by-side (non-causative), then the sentence “the girl is gorping the boy” is only compatible with the causative action. In contrast, if one hears the intransitive sentence, “the girl is gorping”, the verb can be interpreted as being consistent with both the causative scene and the non-causative scene.. Thus the syntactic bootstrapping effect may be larger for transitive conditions, relative to intransitive conditions, because these conditions better distinguish between the two candidate meanings.. Second, children may have more experience with transitive sentences than intransitive sentences. A corpus analysis on parental utterances for 1- to 6-year-olds found that transitive sentences make up approximately 24.36% of all utterances, whereas intransitive sentences only 17.24% [@laakso2007pronouns]. Third, the scenes corresponding to transitive sentences may have been more perceptually salient than those in intransitive conditions. Children were found to have a baseline preference for two actor events over one actor events [e.g., @yuan2012counting], and for synchronous movement over causative movement [e.g., @naigles1993first]. These preferences may make it easier to detect an effect in the transitive condition relative to the intransitive condition.

Importantly, the lack of effect in intransitive sentences calls into question the generalizability of the syntactic bootstrapping effect. It is unclear, for example, what features of transitive sentences make them particularly conducive to verb learning, and what other types of sentence structures syntactic bootstrapping may or may not generalize to. Understanding the linguistic parameters of the effect is important to determining the degree to which syntactic bootstrapping is a plausible general verb learning strategy for young children.

## Limitations and recommendations for future work 

```{r}
sample_summary <- ma_data %>% summarise(
  mean = round(mean(n_1),1), 
  sd = round(sd(n_1), 1)
)

pwr_no_mod_model <- rma.mv(d_calc~1, 
                            V  = d_var_calc,
                            random = ~ 1 |short_cite/same_infant/row_id, 
                            
                  data = ma_data, method = "REML")



d_pwr <- pwr_no_mod_model$b[,1][["intrcpt"]]
pwr_80 <- pwr::pwr.p.test(
  h = d_pwr, 
  sig.level = .05, 
  power = .8)$n

current_pwr <- pwr::pwr.p.test(h = d_pwr, 
           n = sample_summary$mean, 
           sig.level = .05
           )$power
```

Like any method, meta-analysis has a number of limitations.  Most notably, the meta-analytic method is influenced by publication bias of the literature it draws upon. In the present study, we find some evidence for publication bias in the syntactic bootstrapping literature in two different analyses, which suggests that there may be a number of  “missing” null or negative studies in our meta-analysis potentially leading to an overestimation of the overall effect size. Although our sensitivity analysis suggests that the effect size can not be reduced to zero even after assuming the “worst-case scenario”, the presence of publication bias limits the evidential value of the current literature and suggests that the magnitude of the effect should be interpreted with caution. Further, the relatively small effect size also means that large sample sizes are needed to detect moderating factors, meaning that some of the null effects found in our meta-analysis could be the result of insufficient power.

Future research could address the issue of publication bias in several ways.  One way is for researchers to conduct studies with substantially larger sample sizes. The mean sample size of studies in the meta-analysis was approximately `r round(sample_summary$mean,0)`. Based on our meta-analytic effect size estimate, we estimate that studies in our sample had approximately `r 100 * current_pwr`% power to detect a true effect, which is considerably smaller than the typical target of 80%. To reach 80% power, researchers would need about `r round(pwr_80, 0)` participants per condition (substantially more if moderators were tested; SI Sec. 9). Sample size is important because conducting underpowered studies not only increases the false negative rate (Type II error), it also inflates the false positive rate [Type I error, @button2013power; @oakes2017sample]. And, critically, with more false positives, there are more opportunities for publication pressures to influence the literature. Increasing sample size in studies designed to test hypotheses about syntactic bootstrapping would thus reduce the rate of false positives in the literature and decrease publication bias, leading to a more robust estimate of the aggregate effect size. Second, publication bias could be improved by pre-registering study hypotheses, designs, and analytical methods [@nosek2018preregistration]. Pre-registration is a relatively low-cost way for researchers to distinguish both for themselves and for other researchers which decisions in the research process were made before and after seeing the data. By making this distinction explicit, researchers are less likely to inflate the false positive rate through analytical flexibility. Substantial insight into the robustness and strength of the syntactic bootstrapping phenomenon could therefore be gained through a pre-registered, high-powered direct replication of the seminal syntactic bootstrapping studies across one or more labs [e.g., @manybabies2020quantifying].   

A second limitation of the current meta-analysis is the narrow scope of participants in our sample: English-speaking, typically developing children. This homogeneity limits the extent to which our study can shed light on the generalizability of syntactic bootstrapping to other populations. For example, English primarily relies on word order to signal syntactic relations, raising the possibility that children learning languages with more explicit morphosyntactic markers could rely more strongly on syntactic information to infer verb meanings. There are, notably, an increasing number of studies that examine the syntactic bootstrapping effect in children learning a diverse set of languages [e.g. Mandarin: @lee2008mandarin; Korean: @jin2015role; Turkish: @goksun2008turkish] and in children with a range of developmental disorders [e.g. @grela2002lexical;@naigles2011abstractness;@o1997syntactic]. As this literature grows, additional studies can be contributed to the current meta-analysis to systematically examine how differences in language and developmental trajectory interact with the size of the syntactic bootstrapping effect. 

## Conclusion

In sum, syntactic bootstrapping is a prominent proposal for how young children learn an important part of their vocabulary---verbs. Our meta-analysis suggests that although syntactic bootstrapping may be one route to early verb learning, experimental estimates of the effect size  are small relative to other word learning strategies. Further, we find that the  effect may not be robust to a wide range of syntactic structures. Our work highlights the need for pre-registered, high-powered replications of the syntactic bootstrapping effect, and future research that examines how syntactic bootstrapping interacts with other word learning strategies in real-world learning scenarios.  


